configMapGenerator:
- name: example-configmap-1
  literals:
  - COLOR=blue
generatorOptions:
 disableNameSuffixHash: true
 labels:
   kustomize.generated.resource: somevalue
 annotations:
   annotations.only.for.generated: othervalue
