resources:
- deployment.yaml
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-nginx
  spec:
    replicas: 3
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-nginx
  spec:
    template:
      spec:
        containers:
        - name: my-nginx
          resources:
            limits:
              memory: 512Mi
